service: invisibility-score-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    S3_BUCKET_NAME: invisibility-scores-bucket
    STAGE: ${self:provider.stage}
    IS_OFFLINE: ${self:custom.IS_OFFLINE}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:ListBucket
            - s3:GetObject
          Resource:
            - arn:aws:s3:::invisibility-scores-bucket
            - arn:aws:s3:::invisibility-scores-bucket/*
  apiGateway:
    apiKeys:
      - name: my-api-key
    usagePlan:
      throttle:
        burstLimit: 20
        rateLimit: 10
      quota:
        limit: 1000
        period: MONTH

functions:
  superheroHandler:
    handler: dist/handler.superheroHandler
    events:
      - http:
          path: superhero
          method: post
          private: true
  listCSVsHandler:
    handler: dist/listCSVsHandler.listCSVsHandler
    events:
      - http:
          path: list-csvs
          method: get
          private: true

resources:
  Resources:
    InvisibilityScoreBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: invisibility-scores-bucket
        AccessControl: Private

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
  IS_OFFLINE: ${env:IS_OFFLINE, "false"}
